### ISSUE TITLE
Question, (kohana or just php will do)?

### ISSUE THREAD

**Issue by NetLancer** [gleez/cms#770]
Can anyone tell for sure, does site building on Gleez (solid good site) require Kohana framework knowledge, or just php will suffice? I mean if kohana's being used for Gleez cms core or application building logic's also kohana demanding (like case with croogo cms)?  In simple words I'm a user with no framework education but want to use Gleez for my future projects.  Thanx wise folks :)

**Comment by sandeepone** [comment]
Thank you for using Gleez for your future projects. Direct answer; to learn kohana is not required, most of the framework was rewritten for general use cases and application building logic. 

In order to develop on gleezcms one should learn from the existing modules, basic MVC knowledge is required and kohana knowledge will be helpful. Feel free to ask if you have any queries.

**Comment by NetLancer** [comment]
sounds cool, that makes it totally different fron Croogo !  appreciate

**Comment by NetLancer** [comment]
sounds cool, that makes it totally different fron Croogo !  appreciate
